# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Character.create([
  { :name => "The Corrupted Emerald King", :universe_id => 4, :created_at => "2013-04-23 17:08:43", :updated_at => "2013-04-23 17:08:43" },
  { :name => "Glenda the Wicked Witch of the North", :universe_id => 4, :created_at => "2013-04-23 17:09:08", :updated_at => "2013-04-23 17:09:08" },
  { :name => "Good Witch of the West", :universe_id => 4, :created_at => "2013-04-23 17:09:27", :updated_at => "2013-04-23 17:09:27" },
  { :name => "Harry Dresden", :universe_id => 5, :created_at => "2013-05-06 23:51:29", :updated_at => "2013-05-06 23:51:29" },
  { :name => "Karrin Murphy", :universe_id => 5, :created_at => "2013-05-06 23:54:11", :updated_at => "2013-05-06 23:54:11" },
  { :name => "Bob", :universe_id => 5, :created_at => "2013-05-06 23:55:19", :updated_at => "2013-05-06 23:55:19" },
  { :name => "Susan Rodriguez", :universe_id => 5, :created_at => "2013-05-06 23:59:22", :updated_at => "2013-05-06 23:59:22" },
  { :name => "Redd Heart", :universe_id => 6, :created_at => "2013-05-07 17:25:06", :updated_at => "2013-05-07 17:25:06" },
  { :name => "Alyce Heart", :universe_id => 6, :created_at => "2013-05-07 17:25:19", :updated_at => "2013-05-07 17:25:19" },
  { :name => "Marsh Hare", :universe_id => 6, :created_at => "2013-05-07 17:25:42", :updated_at => "2013-05-07 17:25:42" }
], :without_protection => true )



Event.create([
  { :location_id => 3, :scene_id => 7, :created_at => "2013-04-19 09:32:57", :updated_at => "2013-04-19 09:32:57" },
  { :location_id => 6, :scene_id => 8, :created_at => "2013-04-19 23:55:02", :updated_at => "2013-04-19 23:55:02" },
  { :location_id => 4, :scene_id => 6, :created_at => "2013-05-02 07:11:57", :updated_at => "2013-05-02 07:11:57" },
  { :location_id => 14, :scene_id => 8, :created_at => "2013-05-02 08:04:38", :updated_at => "2013-05-02 08:04:38" },
  { :location_id => 15, :scene_id => 8, :created_at => "2013-05-02 08:04:38", :updated_at => "2013-05-02 08:04:38" },
  { :location_id => 21, :scene_id => 8, :created_at => "2013-05-02 08:04:38", :updated_at => "2013-05-02 08:04:38" },
  { :location_id => 26, :scene_id => 8, :created_at => "2013-05-02 08:04:38", :updated_at => "2013-05-02 08:04:38" },
  { :location_id => 27, :scene_id => 8, :created_at => "2013-05-02 08:04:38", :updated_at => "2013-05-02 08:04:38" },
  { :location_id => 28, :scene_id => 8, :created_at => "2013-05-02 08:04:38", :updated_at => "2013-05-02 08:04:38" },
  { :location_id => 32, :scene_id => 10, :created_at => "2013-05-07 00:26:02", :updated_at => "2013-05-07 00:26:02" },
  { :location_id => 33, :scene_id => 11, :created_at => "2013-05-07 16:56:50", :updated_at => "2013-05-07 16:56:50" }
], :without_protection => true )



Location.create([
  { :name => "Yellow Brick Road", :universe_id => 4, :created_at => "2013-04-23 17:10:26", :updated_at => "2013-04-23 17:10:26" },
  { :name => "West Village", :universe_id => 4, :created_at => "2013-04-23 17:10:36", :updated_at => "2013-04-23 17:10:36" },
  { :name => "Mushroom Forest", :universe_id => 4, :created_at => "2013-04-23 17:10:51", :updated_at => "2013-04-23 17:10:51" },
  { :name => "Harry Dresden's office", :universe_id => 5, :created_at => "2013-05-07 00:07:00", :updated_at => "2013-05-07 00:07:00" },
  { :name => "Madison Hotel", :universe_id => 5, :created_at => "2013-05-07 15:00:51", :updated_at => "2013-05-07 15:00:51" },
  { :name => "Yellow Brick Road", :universe_id => 6, :created_at => "2013-05-07 17:38:00", :updated_at => "2013-05-07 17:38:00" }
], :without_protection => true )



Npc.create([
  { :character_id => 26, :scene_id => 5, :created_at => "2013-04-23 17:11:54", :updated_at => "2013-04-23 17:11:54" },
  { :character_id => 28, :scene_id => 6, :created_at => "2013-05-02 06:32:31", :updated_at => "2013-05-02 06:32:31" },
  { :character_id => 27, :scene_id => 7, :created_at => "2013-05-02 06:43:51", :updated_at => "2013-05-02 06:43:51" },
  { :character_id => 28, :scene_id => 7, :created_at => "2013-05-02 06:43:51", :updated_at => "2013-05-02 06:43:51" },
  { :character_id => 27, :scene_id => 4, :created_at => "2013-05-02 07:25:04", :updated_at => "2013-05-02 07:25:04" },
  { :character_id => 28, :scene_id => 4, :created_at => "2013-05-02 07:25:04", :updated_at => "2013-05-02 07:25:04" },
  { :character_id => 28, :scene_id => 3, :created_at => "2013-05-02 07:26:07", :updated_at => "2013-05-02 07:26:07" },
  { :character_id => 20, :scene_id => 1, :created_at => "2013-05-02 07:28:23", :updated_at => "2013-05-02 07:28:23" },
  { :character_id => 20, :scene_id => 2, :created_at => "2013-05-02 07:29:19", :updated_at => "2013-05-02 07:29:19" },
  { :character_id => 20, :scene_id => 8, :created_at => "2013-05-02 08:04:38", :updated_at => "2013-05-02 08:04:38" },
  { :character_id => 21, :scene_id => 8, :created_at => "2013-05-02 08:04:38", :updated_at => "2013-05-02 08:04:38" },
  { :character_id => 22, :scene_id => 8, :created_at => "2013-05-02 08:04:38", :updated_at => "2013-05-02 08:04:38" },
  { :character_id => 33, :scene_id => 10, :created_at => "2013-05-07 00:26:02", :updated_at => "2013-05-07 00:26:02" },
  { :character_id => 33, :scene_id => 11, :created_at => "2013-05-07 16:56:50", :updated_at => "2013-05-07 16:56:50" },
  { :character_id => 35, :scene_id => 11, :created_at => "2013-05-07 16:56:50", :updated_at => "2013-05-07 16:56:50" }
], :without_protection => true )



Part.create([
  { :content => "test content", :partible_id => 28, :partible_type => "Character", :created_at => "2013-05-06 19:56:09", :updated_at => "2013-05-06 19:56:09" },
  { :content => "Harry Blackstone Copperfield Dresden is a male human wizard, working as a private investigator out of Chicago, USA. He is the protagonist and first person narrator of The Dresden Files series.", :partible_id => 33, :partible_type => "Character", :created_at => "2013-05-06 23:52:04", :updated_at => "2013-05-06 23:52:04" },
  { :content => "A human woman, and member of the Chicago Police Department at the Special Investigations division", :partible_id => 35, :partible_type => "Character", :created_at => "2013-05-06 23:54:43", :updated_at => "2013-05-06 23:54:43" },
  { :content => "Bob is an air spirit of intellect inhabiting a human skull. He acts as Harry Lab assistant and living encyclopedia of Magic.  He's been assisting wizards since the dark ages. Bob doesn't forget anything ever. Bob has a great experience in applied magic from being owned by several wizards, as well as innate knowledge of the rules of the supernatural and their current status.", :partible_id => 37, :partible_type => "Character", :created_at => "2013-05-06 23:56:27", :updated_at => "2013-05-06 23:56:27" },
  { :content => "A former investigative reporter for the paranormal newspaper The Midwestern Arcane. It's through her investigations that she encountered Harry", :partible_id => 39, :partible_type => "Character", :created_at => "2013-05-07 00:00:01", :updated_at => "2013-05-07 00:00:01" },
  { :content => "The office is located in a building in midtown Chicago. The office's door holds a frosted-glass window, with the lettering \"HARRY DRESDEN, WIZARD\" painted on.", :partible_id => 32, :partible_type => "Location", :created_at => "2013-05-07 00:08:04", :updated_at => "2013-05-07 00:08:04" },
  { :content => "Directly in front of my office door is a table arranged with a series of pamphlets with titles like Real\r\nWitches Don't Float So Good , and Magic in the Twenty-first Century.", :partible_id => 32, :partible_type => "Location", :created_at => "2013-05-07 00:20:33", :updated_at => "2013-05-07 00:20:33" },
  { :content => "To the right of the door is a wall lined with filing cabinets and a couple of easy chairs. ", :partible_id => 32, :partible_type => "Location", :created_at => "2013-05-07 00:21:11", :updated_at => "2013-05-07 00:21:11" },
  { :content => "The desk is in the back corner, to the right as you come in the door, diagonal from it. It's a corner office.\r\nThere are windows on either of the outside walls with shades were, as usual, drawn. ", :partible_id => 32, :partible_type => "Location", :created_at => "2013-05-07 00:22:29", :updated_at => "2013-05-07 00:22:29" },
  { :content => "The overhead fan, in the center of the room,makes a tired little groan on every rotation.", :partible_id => 32, :partible_type => "Location", :created_at => "2013-05-07 00:23:55", :updated_at => "2013-05-07 00:23:55" },
  { :content => "Unholy Undead Abomination.", :partible_id => 42, :partible_type => "Character", :created_at => "2013-05-07 17:26:06", :updated_at => "2013-05-07 17:26:06" }
], :without_protection => true )



Role.create([
  { :name => "admin", :resource_id => nil, :resource_type => nil, :created_at => "2013-04-23 04:01:41", :updated_at => "2013-04-23 04:01:41" },
  { :name => "author", :resource_id => nil, :resource_type => nil, :created_at => "2013-04-23 04:01:41", :updated_at => "2013-04-23 04:01:41" },
  { :name => "collaborator", :resource_id => nil, :resource_type => nil, :created_at => "2013-04-23 04:01:41", :updated_at => "2013-04-23 04:01:41" }
], :without_protection => true )



Scene.create([
  { :name => "follow the yellow brick", :branch => nil, :universe_id => 4, :created_at => "2013-04-23 17:11:54", :updated_at => "2013-04-24 09:21:56" },
  { :name => "Harry in the office", :branch => nil, :universe_id => 5, :created_at => "2013-05-07 00:26:02", :updated_at => "2013-05-07 00:26:02" },
  { :name => "at the hotel", :branch => nil, :universe_id => 5, :created_at => "2013-05-07 16:56:50", :updated_at => "2013-05-07 16:56:50" }
], :without_protection => true )



Story.create([
  { :name => "another day in the OZ", :chapter => 1, :universe_id => 4, :created_at => "2013-04-24 09:23:21", :updated_at => "2013-04-24 09:23:21" },
  { :name => "Storm Front", :chapter => 1, :universe_id => 5, :created_at => "2013-05-07 00:57:57", :updated_at => "2013-05-07 00:57:57" }
], :without_protection => true )



Storyline.create([
  { :story_id => 8, :scene_id => 5, :created_at => "2013-04-24 09:38:32", :updated_at => "2013-04-24 09:38:32" },
  { :story_id => 9, :scene_id => 5, :created_at => "2013-04-24 09:39:12", :updated_at => "2013-04-24 09:39:12" },
  { :story_id => 6, :scene_id => 5, :created_at => "2013-04-24 17:51:00", :updated_at => "2013-04-24 17:51:00" },
  { :story_id => 7, :scene_id => 10, :created_at => "2013-05-07 00:57:57", :updated_at => "2013-05-07 00:57:57" },
  { :story_id => 7, :scene_id => 11, :created_at => "2013-05-07 17:00:10", :updated_at => "2013-05-07 17:00:10" }
], :without_protection => true )



Universe.create([
  { :name => "Under OZ", :user_id => 2, :created_at => "2013-04-23 17:05:09", :updated_at => "2013-04-23 17:05:09" },
  { :name => "Dresdenverse", :user_id => 1, :created_at => "2013-05-06 23:47:09", :updated_at => "2013-05-06 23:47:09" },
  { :name => "Wonder OZ", :user_id => 3, :created_at => "2013-05-07 16:57:25", :updated_at => "2013-05-07 16:57:25" }
], :without_protection => true )



User.create([
  { :email => "johncockrum1@gmail.com", :encrypted_password => "$2a$10$TQvApDfi9E1eaxWu/bjQ7e4RQMkll3pwB/jaLrS/2IFWKJ.QGm6FG", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => "2013-05-06 09:32:05", :sign_in_count => 6, :current_sign_in_at => "2013-05-06 19:16:12", :last_sign_in_at => "2013-05-06 09:32:05", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :created_at => "2013-04-23 04:01:41", :updated_at => "2013-05-06 19:16:12", :name => "Johnny" },
  { :email => "dreagunluthe@gmail.com", :encrypted_password => "$2a$10$sWeH0lkyW//r3Hgg8bVh8.3Jk.LUpk5V6QXOiODKph3u1DzjIhGEq", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 1, :current_sign_in_at => "2013-05-07 16:56:58", :last_sign_in_at => "2013-05-07 16:56:58", :current_sign_in_ip => "192.168.2.127", :last_sign_in_ip => "192.168.2.127", :created_at => "2013-05-07 16:56:58", :updated_at => "2013-05-07 16:56:58", :name => "Patrick" }
], :without_protection => true )


