# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
# encoding: utf-8
# Autogenerated by the db:seed:dump task

puts 'ROLES'
YAML.load(ENV['ROLES']).each do |role|
  Role.find_or_create_by_name({ :name => role }, :without_protection => true)
  puts 'role: ' << role
end

puts 'DEFAULT USERS'
user = User.find_or_create_by_email :name => ENV['ADMIN_NAME'].dup, :email => ENV['ADMIN_EMAIL'].dup, :password => ENV['ADMIN_PASSWORD'].dup, :password_confirmation => ENV['ADMIN_PASSWORD'].dup
puts 'user: ' << user.name
user.add_role :admin

puts 'CHARACTERS'
Character.create([
  { :name => "char 1", :universe_id => 1, :created_at => "2013-04-19 07:58:04", :updated_at => "2013-04-19 07:58:04" },
  { :name => "Char 2", :universe_id => 1, :created_at => "2013-04-19 07:58:15", :updated_at => "2013-04-19 07:58:15" },
  { :name => "Char 3", :universe_id => 1, :created_at => "2013-04-19 07:58:27", :updated_at => "2013-04-19 07:58:27" },
  { :name => "Aela the Huntress", :universe_id => 2, :created_at => "2013-04-19 23:26:03", :updated_at => "2013-04-19 23:26:03" },
  { :name => "Barbas", :universe_id => 2, :created_at => "2013-04-19 23:26:58", :updated_at => "2013-04-19 23:26:58" },
  { :name => "Elisif the Fair", :universe_id => 2, :created_at => "2013-04-19 23:28:18", :updated_at => "2013-04-19 23:28:18" },
  { :name => "Ralof", :universe_id => 2, :created_at => "2013-04-22 05:38:13", :updated_at => "2013-04-22 05:38:13" },
  { :name => "Ulfric Stormcloak ", :universe_id => 2, :created_at => "2013-04-22 05:38:45", :updated_at => "2013-04-22 05:38:45" },
  { :name => "Alduin", :universe_id => 2, :created_at => "2013-04-22 05:39:06", :updated_at => "2013-04-22 05:39:06" },
  { :name => "Hadvar", :universe_id => 2, :created_at => "2013-04-22 05:39:30", :updated_at => "2013-04-22 05:39:30" },
  { :name => "Gunjar", :universe_id => 2, :created_at => "2013-04-22 05:40:03", :updated_at => "2013-04-22 05:40:03" },
  { :name => "Gerdur", :universe_id => 2, :created_at => "2013-04-22 05:40:27", :updated_at => "2013-04-22 05:40:27" },
  { :name => "Alvor", :universe_id => 2, :created_at => "2013-04-22 05:40:57", :updated_at => "2013-04-22 05:40:57" }
], :without_protection => true )


puts 'EVENTS'
Event.create([
  { :location_id => 3, :scene_id => 7, :created_at => "2013-04-19 09:32:57", :updated_at => "2013-04-19 09:32:57" },
  { :location_id => 6, :scene_id => 8, :created_at => "2013-04-19 23:55:02", :updated_at => "2013-04-19 23:55:02" },
  { :location_id => 6, :scene_id => 9, :created_at => "2013-04-19 23:56:55", :updated_at => "2013-04-19 23:56:55" },
  { :location_id => 9, :scene_id => 4, :created_at => "2013-04-22 05:35:53", :updated_at => "2013-04-22 05:35:53" },
  { :location_id => 11, :scene_id => 4, :created_at => "2013-04-22 05:53:35", :updated_at => "2013-04-22 05:53:35" },
  { :location_id => 12, :scene_id => 4, :created_at => "2013-04-22 06:06:42", :updated_at => "2013-04-22 06:06:42" },
  { :location_id => 13, :scene_id => 4, :created_at => "2013-04-22 06:06:42", :updated_at => "2013-04-22 06:06:42" },
  { :location_id => 10, :scene_id => 6, :created_at => "2013-04-22 06:24:28", :updated_at => "2013-04-22 06:24:28" },
  { :location_id => 14, :scene_id => 6, :created_at => "2013-04-22 06:28:36", :updated_at => "2013-04-22 06:28:36" },
  { :location_id => 15, :scene_id => 6, :created_at => "2013-04-22 06:28:36", :updated_at => "2013-04-22 06:28:36" },
  { :location_id => 16, :scene_id => 6, :created_at => "2013-04-22 06:28:36", :updated_at => "2013-04-22 06:28:36" },
  { :location_id => 17, :scene_id => 6, :created_at => "2013-04-22 06:28:36", :updated_at => "2013-04-22 06:28:36" }
], :without_protection => true )


puts 'LOCATIONS'
Location.create([
  { :name => "The Hill", :universe_id => 1, :created_at => "2013-04-19 09:29:31", :updated_at => "2013-04-19 09:29:31" },
  { :name => "The Forest", :universe_id => 1, :created_at => "2013-04-19 09:29:45", :updated_at => "2013-04-19 09:29:45" },
  { :name => "The Hill Top", :universe_id => 1, :created_at => "2013-04-19 09:29:57", :updated_at => "2013-04-19 09:29:57" },
  { :name => "In town", :universe_id => 1, :created_at => "2013-04-19 09:30:10", :updated_at => "2013-04-19 09:30:10" },
  { :name => "Down town", :universe_id => 1, :created_at => "2013-04-19 09:30:23", :updated_at => "2013-04-19 09:30:23" },
  { :name => "Dawnstar", :universe_id => 2, :created_at => "2013-04-19 23:22:46", :updated_at => "2013-04-19 23:22:46" },
  { :name => "Falkreath", :universe_id => 2, :created_at => "2013-04-19 23:23:18", :updated_at => "2013-04-19 23:23:18" },
  { :name => "Markarth", :universe_id => 2, :created_at => "2013-04-19 23:23:51", :updated_at => "2013-04-19 23:23:51" },
  { :name => "Helgen", :universe_id => 2, :created_at => "2013-04-22 05:30:52", :updated_at => "2013-04-22 05:30:52" },
  { :name => "Riverwood", :universe_id => 2, :created_at => "2013-04-22 05:41:52", :updated_at => "2013-04-22 05:41:52" },
  { :name => "Helgen Keep", :universe_id => 2, :created_at => "2013-04-22 05:53:12", :updated_at => "2013-04-22 05:53:12" },
  { :name => "Helgen cavern", :universe_id => 2, :created_at => "2013-04-22 05:55:15", :updated_at => "2013-04-22 05:55:15" },
  { :name => "Helgen streets", :universe_id => 2, :created_at => "2013-04-22 05:56:11", :updated_at => "2013-04-22 05:56:11" },
  { :name => " The Three Guardian Stones", :universe_id => 2, :created_at => "2013-04-22 06:25:06", :updated_at => "2013-04-22 06:25:06" },
  { :name => "Alvor and Sigrid's House", :universe_id => 2, :created_at => "2013-04-22 06:26:13", :updated_at => "2013-04-22 06:26:13" },
  { :name => "Riverwood Trader", :universe_id => 2, :created_at => "2013-04-22 06:26:40", :updated_at => "2013-04-22 06:26:40" },
  { :name => "Sleeping Giant Inn", :universe_id => 2, :created_at => "2013-04-22 06:26:59", :updated_at => "2013-04-22 06:26:59" }
], :without_protection => true )


puts 'NPCS'
Npc.create([
  { :character_id => 1, :scene_id => 2, :created_at => "2013-04-19 08:57:10", :updated_at => "2013-04-19 08:57:10" },
  { :character_id => 2, :scene_id => 2, :created_at => "2013-04-19 08:57:10", :updated_at => "2013-04-19 08:57:10" },
  { :character_id => 1, :scene_id => 3, :created_at => "2013-04-19 08:58:20", :updated_at => "2013-04-19 08:58:20" },
  { :character_id => 2, :scene_id => 3, :created_at => "2013-04-19 08:58:20", :updated_at => "2013-04-19 08:58:20" },
  { :character_id => 1, :scene_id => 4, :created_at => "2013-04-19 09:06:44", :updated_at => "2013-04-19 09:06:44" },
  { :character_id => 1, :scene_id => 7, :created_at => "2013-04-19 09:32:57", :updated_at => "2013-04-19 09:32:57" },
  { :character_id => 2, :scene_id => 7, :created_at => "2013-04-19 09:32:57", :updated_at => "2013-04-19 09:32:57" },
  { :character_id => 3, :scene_id => 7, :created_at => "2013-04-19 09:32:57", :updated_at => "2013-04-19 09:32:57" },
  { :character_id => 6, :scene_id => 8, :created_at => "2013-04-19 23:55:02", :updated_at => "2013-04-19 23:55:02" },
  { :character_id => 6, :scene_id => 9, :created_at => "2013-04-19 23:56:55", :updated_at => "2013-04-19 23:56:55" },
  { :character_id => 7, :scene_id => 4, :created_at => "2013-04-22 05:43:59", :updated_at => "2013-04-22 05:43:59" },
  { :character_id => 8, :scene_id => 4, :created_at => "2013-04-22 05:43:59", :updated_at => "2013-04-22 05:43:59" },
  { :character_id => 9, :scene_id => 4, :created_at => "2013-04-22 05:43:59", :updated_at => "2013-04-22 05:43:59" },
  { :character_id => 10, :scene_id => 4, :created_at => "2013-04-22 05:43:59", :updated_at => "2013-04-22 05:43:59" },
  { :character_id => 11, :scene_id => 4, :created_at => "2013-04-22 05:43:59", :updated_at => "2013-04-22 05:43:59" },
  { :character_id => 1, :scene_id => 6, :created_at => "2013-04-22 06:24:28", :updated_at => "2013-04-22 06:24:28" },
  { :character_id => 7, :scene_id => 6, :created_at => "2013-04-22 06:28:36", :updated_at => "2013-04-22 06:28:36" },
  { :character_id => 10, :scene_id => 6, :created_at => "2013-04-22 06:28:36", :updated_at => "2013-04-22 06:28:36" },
  { :character_id => 12, :scene_id => 6, :created_at => "2013-04-22 06:28:36", :updated_at => "2013-04-22 06:28:36" },
  { :character_id => 13, :scene_id => 6, :created_at => "2013-04-22 06:28:36", :updated_at => "2013-04-22 06:28:36" }
], :without_protection => true )


puts 'PARTS'
Part.create([
  { :content => "this is app", :partible_id => 1, :partible_type => "Universe", :created_at => "2013-04-18 15:14:50", :updated_at => "2013-04-18 15:14:50" },
  { :content => "Universe the second", :partible_id => 2, :partible_type => "Universe", :created_at => "2013-04-19 23:18:33", :updated_at => "2013-04-19 23:18:33" },
  { :content => "A garrison town on the northern coast of Skyrim. Capital City of The Pale It was after the destruction of a fortress in Dawnstar during 2E 283 that Potentate Versidue-Shaie declared martial law, leading to one of the most brutal and bloody periods in the history of Tamriel. Dawnstar is one of the northern most cities in Skyrim along with Solitude and Winterhold.", :partible_id => 6, :partible_type => "Location", :created_at => "2013-04-19 23:22:59", :updated_at => "2013-04-19 23:22:59" },
  { :content => "A city in south-western Skyrim, Capital of Falkreath Hold. Close to the border with both and Hammerfell. Just across the border in Hammerfell lies the town of Elinhir. Falkreath is known for its cemetery, which dominates the southern part of the town.", :partible_id => 7, :partible_type => "Location", :created_at => "2013-04-19 23:23:34", :updated_at => "2013-04-19 23:23:34" },
  { :content => "A city in west-central Skyrim, the capital city of The Reach. Notable for possessing the Imperial College of the Voice, which was founded by Tiber Septim to restore the Voice to the art of warfare. Half of the town is controlled by a wealth family known as the Silver-Bloods, and violence runs rampant throughout most of the city because of the Forsworn.", :partible_id => 8, :partible_type => "Location", :created_at => "2013-04-19 23:24:04", :updated_at => "2013-04-19 23:24:04" },
  { :content => "Aela the Huntress is a lycanthropic female Nord in The Elder Scrolls V: Skyrim. She is a member of The Companions and one of the five members of The Circle. Residing in Jorrvaskr with the other Companions, Aela offers lycanthropy, deep into that questline. Additionally, she becomes a candidate for marriage, as well as a follower.", :partible_id => 6, :partible_type => "Character", :created_at => "2013-04-19 23:26:39", :updated_at => "2013-04-19 23:26:39" },
  { :content => "A dog found along the road outside Falkreath. Barbas is Clavicus Vile's companion, a supernatural creature that usually takes the form of a dog.", :partible_id => 7, :partible_type => "Character", :created_at => "2013-04-19 23:27:50", :updated_at => "2013-04-19 23:27:50" },
  { :content => "Elisif the Fair is the current Jarl of Solitude and the widow of High King Torygg, the last elected High King of Skyrim prior to the Stormcloak Rebellion. While Elisif holds court at her palace in Solitude, the majority of her courtly duties are handled by her steward, Falk Firebeard. Bolgeir Bearclaw serves as her Housecarl, while Bryling and Erikur serve as her Thanes.", :partible_id => 8, :partible_type => "Character", :created_at => "2013-04-19 23:28:52", :updated_at => "2013-04-19 23:28:52" },
  { :content => "'ve been captured by the Empire and been sentenced to death alongside Stormcloak rebels. We were being taken to Helgen, but before I could be executed Alduin appeared and attacked the town. I need to find a way out of the town.", :partible_id => 8, :partible_type => "Scene", :created_at => "2013-04-19 23:55:46", :updated_at => "2013-04-19 23:55:46" },
  { :content => "After escaping from the dragon attack at Helgen, it's necessary to follow the advice received that leads to Riverwood. It is possible to gather supplies and prepare for a trip to Whiterun to report the recent events to Jarl Balgruuf.", :partible_id => 9, :partible_type => "Scene", :created_at => "2013-04-19 23:57:04", :updated_at => "2013-04-19 23:57:04" },
  { :content => "Helgen is a thriving town and keep on the southern border of Skyrim with Cyrodiil, the keep is controlled by the Imperial Legion.", :partible_id => 9, :partible_type => "Location", :created_at => "2013-04-22 05:33:24", :updated_at => "2013-04-22 05:33:24" },
  { :content => "It has a few distinguishing features: a wall, which is unusual for a smaller town. It also has a large keep, which is unusual for anywhere but forts and walled hold capitals. It is possible that it is the Imperial Second Chain in power in Skyrim, behind Castle Dour, considering the strategic location not far from the southern border with Cyrodiil and mid-point for the north-easterly trade routes to Whiterun.", :partible_id => 9, :partible_type => "Location", :created_at => "2013-04-22 05:35:06", :updated_at => "2013-04-22 05:35:06" },
  { :content => "I've been captured by the Empire and been sentenced to death alongside Stormcloak rebels. We were being taken to Helgen, but before I could be executed Alduin appeared and attacked the town. I need to find a way out of the town.", :partible_id => 4, :partible_type => "Scene", :created_at => "2013-04-22 05:44:48", :updated_at => "2013-04-22 05:44:48" },
  { :content => "Just before the Imperial Headsman being executed, Alduin arrives and disrupts the execution. With the execution stopped and the guards in chaos, you escape custody. Running towards a nearby tower, you meet up with Ralof and Ulfric Stormcloak, leader of the Stormcloaks, who also managed to escape.", :partible_id => 4, :partible_type => "Scene", :created_at => "2013-04-22 05:45:36", :updated_at => "2013-04-22 05:46:58" },
  { :content => "Alduin blasts a hole in the tower next to you, killing another Stormcloak in the process. Ralof will instruct you to jump out of the tower from the hole into a nearby inn, with the promise that he will meet up with you when he can. After jumping down and exiting the inn, you find that Helgen has become heavily damaged in quite a short time, with many buildings damaged and burning. As you you run into the street you meet an Imperial Soldier, Hadvar, who will then lead you to the Helgen Keep. At the entrance of The Keep, Ralof catches up with you.", :partible_id => 4, :partible_type => "Scene", :created_at => "2013-04-22 05:50:22", :updated_at => "2013-04-22 05:50:22" },
  { :content => "You now have to choose to either leave with Hadvar or Ralof. If you side with Hadvar, you will fight stormcloaks. If you side with Ralof you will fight soldiers.", :partible_id => 4, :partible_type => "Scene", :created_at => "2013-04-22 05:52:11", :updated_at => "2013-04-22 06:02:07" },
  { :content => "Upon entering the keep, you and discover the body of a dead Stormcloak, Gunjar. After freeing you from your bindings, you to take Gunjar's gear for your own use, as he won't be needing it. There are 2 locked doors. Luckily, an Imperial Captain and Imperial Soldier will come through and open the door from the other side. Once they open the door, Going through the now opened up path, you will discover a store room, with two more Imperial Soldiers gathering supplies.", :partible_id => 4, :partible_type => "Scene", :created_at => "2013-04-22 05:59:48", :updated_at => "2013-04-22 06:02:34" },
  { :content => "Continuing down, you arrive at a battle between an Imperial torturer and his Assistant against two Stormcloaks. ", :partible_id => 4, :partible_type => "Scene", :created_at => "2013-04-22 06:00:48", :updated_at => "2013-04-22 06:00:48" },
  { :content => "When you have finished, you go through a hallway lined with cells. One of these cells consists of a skeleton, Bone Meal, and a coin purse. After that, you enter a room with prisoners in cages. All of them are deceased, and there are 3 more skeletons, all of which also carry Bone Meal, and they usually carry septims on them as well. In one of the cages, there is a dead Stormcloak wearing Ragged Robes.", :partible_id => 4, :partible_type => "Scene", :created_at => "2013-04-22 06:03:10", :updated_at => "2013-04-22 06:03:10" },
  { :content => "You eventually enter a natural cave, filled with soldiers guarding it.There are a few archers and swordsmen in the cavern, along with another soldier wearing heavy armor. ", :partible_id => 4, :partible_type => "Scene", :created_at => "2013-04-22 06:04:13", :updated_at => "2013-04-22 06:04:13" },
  { :content => "Once you've dealt with that, you will see an exit to the cave. Once free, you will see Alduin fly overhead. Ralof will direct the player to his sister, Gerdur, who lives in Riverwood, or Hadvar will direct the player to his uncle, Alvor, who lives in Riverwood.", :partible_id => 4, :partible_type => "Scene", :created_at => "2013-04-22 06:04:50", :updated_at => "2013-04-22 06:06:04" },
  { :content => "On the way to Riverwood along the path taken are three Guardian Stones: The Warrior, The Mage, and The Thief.", :partible_id => 6, :partible_type => "Scene", :created_at => "2013-04-22 06:31:39", :updated_at => "2013-04-22 06:34:24" },
  { :content => "After arrival in the village, assuming you traveled the entire way with your Helgen-met companion, the hero is led to a house depending on who was followed in the opening quest. You will be offered a gift of supplies. All of the items offered can be taken without anyone complaining. The Riverwood contact will also recommend that a report be made to Jarl Balgruuf, in Whiterun, regarding all of the events that have transpired.", :partible_id => 6, :partible_type => "Scene", :created_at => "2013-04-22 06:31:55", :updated_at => "2013-04-22 06:35:22" }
], :without_protection => true )


puts 'SCENES'
Scene.create([
  { :name => "Unbound",  :universe_id => 2, :created_at => "2013-04-19 23:55:02", :updated_at => "2013-04-19 23:55:02" },
  { :name => "Before the Storm", :universe_id => 2, :created_at => "2013-04-22 06:24:28", :updated_at => "2013-04-22 06:24:28" }
], :without_protection => true )


puts 'STORIES'
Story.create([
  { :name => "Main Story", :universe_id => 2, :created_at => "2013-04-20 00:32:44", :updated_at => "2013-04-20 00:32:44" },
  { :name => "The College of the Winterhold", :universe_id => 2, :created_at => "2013-04-20 00:44:06", :updated_at => "2013-04-22 04:42:25" },
  { :name => "Side Quests", :universe_id => 2, :created_at => "2013-04-20 00:44:20", :updated_at => "2013-04-20 00:44:20" },
  { :name => "Main Story", :universe_id => 1, :created_at => "2013-04-20 17:34:19", :updated_at => "2013-04-20 17:34:19" },
  { :name => "Main Story", :universe_id => 1, :created_at => "2013-04-20 17:44:21", :updated_at => "2013-04-20 17:44:21" }
], :without_protection => true )


puts 'STORYLINES'
Storyline.create([
  { :story_id => 4, :scene_id => 5, :created_at => "2013-04-20 17:34:19", :updated_at => "2013-04-20 17:34:19" },
  { :story_id => 5, :scene_id => 5, :created_at => "2013-04-20 17:44:21", :updated_at => "2013-04-20 17:44:21" },
  { :story_id => 6, :scene_id => 5, :created_at => "2013-04-20 17:47:54", :updated_at => "2013-04-20 17:47:54" }
], :without_protection => true )


puts 'UNIVERSES'
Universe.create([
  { :name => "test 1", :created_at => "2013-04-18 15:14:33", :updated_at => "2013-04-18 15:14:33" },
  { :name => "test 2", :created_at => "2013-04-19 23:18:22", :updated_at => "2013-04-19 23:18:22" }
], :without_protection => true )
