require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PhysicsController do

  # This should return the minimal set of attributes required to create a valid
  # Physic. As you add validations to Physic, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "position" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PhysicsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all physics as @physics" do
      physic = Physic.create! valid_attributes
      get :index, {}, valid_session
      assigns(:physics).should eq([physic])
    end
  end

  describe "GET show" do
    it "assigns the requested physic as @physic" do
      physic = Physic.create! valid_attributes
      get :show, {:id => physic.to_param}, valid_session
      assigns(:physic).should eq(physic)
    end
  end

  describe "GET new" do
    it "assigns a new physic as @physic" do
      get :new, {}, valid_session
      assigns(:physic).should be_a_new(Physic)
    end
  end

  describe "GET edit" do
    it "assigns the requested physic as @physic" do
      physic = Physic.create! valid_attributes
      get :edit, {:id => physic.to_param}, valid_session
      assigns(:physic).should eq(physic)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Physic" do
        expect {
          post :create, {:physic => valid_attributes}, valid_session
        }.to change(Physic, :count).by(1)
      end

      it "assigns a newly created physic as @physic" do
        post :create, {:physic => valid_attributes}, valid_session
        assigns(:physic).should be_a(Physic)
        assigns(:physic).should be_persisted
      end

      it "redirects to the created physic" do
        post :create, {:physic => valid_attributes}, valid_session
        response.should redirect_to(Physic.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved physic as @physic" do
        # Trigger the behavior that occurs when invalid params are submitted
        Physic.any_instance.stub(:save).and_return(false)
        post :create, {:physic => { "position" => "invalid value" }}, valid_session
        assigns(:physic).should be_a_new(Physic)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Physic.any_instance.stub(:save).and_return(false)
        post :create, {:physic => { "position" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested physic" do
        physic = Physic.create! valid_attributes
        # Assuming there are no other physics in the database, this
        # specifies that the Physic created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Physic.any_instance.should_receive(:update_attributes).with({ "position" => "MyString" })
        put :update, {:id => physic.to_param, :physic => { "position" => "MyString" }}, valid_session
      end

      it "assigns the requested physic as @physic" do
        physic = Physic.create! valid_attributes
        put :update, {:id => physic.to_param, :physic => valid_attributes}, valid_session
        assigns(:physic).should eq(physic)
      end

      it "redirects to the physic" do
        physic = Physic.create! valid_attributes
        put :update, {:id => physic.to_param, :physic => valid_attributes}, valid_session
        response.should redirect_to(physic)
      end
    end

    describe "with invalid params" do
      it "assigns the physic as @physic" do
        physic = Physic.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Physic.any_instance.stub(:save).and_return(false)
        put :update, {:id => physic.to_param, :physic => { "position" => "invalid value" }}, valid_session
        assigns(:physic).should eq(physic)
      end

      it "re-renders the 'edit' template" do
        physic = Physic.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Physic.any_instance.stub(:save).and_return(false)
        put :update, {:id => physic.to_param, :physic => { "position" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested physic" do
      physic = Physic.create! valid_attributes
      expect {
        delete :destroy, {:id => physic.to_param}, valid_session
      }.to change(Physic, :count).by(-1)
    end

    it "redirects to the physics list" do
      physic = Physic.create! valid_attributes
      delete :destroy, {:id => physic.to_param}, valid_session
      response.should redirect_to(physics_url)
    end
  end

end
